# Generated by Django 5.2.8 on 2026-07-08 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0007_escola_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto Informativo'), ('curso', 'Curso do Mês')], default='curso', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True, help_text='Usado apenas se tipo=texto')),
                ('data_inicio', models.DateField(blank=True, help_text='Usado apenas se tipo=curso', null=True)),
                ('data_fim', models.DateField(blank=True, help_text='Usado apenas se tipo=curso', null=True)),
                ('dias_semana', models.CharField(blank=True, help_text='Ex: Seg, Qua, Sex', max_length=100)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_conteudo', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Bloco de Conteúdo',
                'verbose_name_plural': 'Blocos de Conteúdo',
                'ordering': ['ordem', '-id'],
            },
        ),
    ]
