# Generated by Django 5.2.8 on 2026-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoEmentaPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Curso')),
                ('texto', models.TextField(verbose_name='Texto da Ementa')),
                ('ativo', models.BooleanField(default=True, help_text='Exibir na página pública?')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Usado para ordenar a lista')),
            ],
            options={
                'verbose_name': 'Curso/Ementa Pública',
                'verbose_name_plural': 'Cursos/Ementas Públicas',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
