# Generated by Django 5.2.8 on 2025-11-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], max_length=20)),
                ('email_principal', models.EmailField(max_length=254, unique=True)),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_principal', models.CharField(max_length=20)),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_rua', models.CharField(max_length=255)),
                ('endereco_numero', models.CharField(max_length=10)),
                ('endereco_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_bairro', models.CharField(max_length=100)),
                ('endereco_cidade', models.CharField(max_length=100)),
                ('endereco_estado', models.CharField(max_length=2)),
                ('endereco_cep', models.CharField(max_length=9)),
                ('empresa_trabalha', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('cursos_interesse', models.TextField(blank=True, help_text='Separar os cursos por vírgula', null=True)),
                ('score_aluno', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='escolas.escola')),
            ],
        ),
    ]
