# Generated by Django 5.2.8 on 2025-11-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('cursos', '0003_inscricao_status'),
        ('escolas', '0002_escola_coordenador_user_alter_escola_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cargo_empresa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email_secundario',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='empresa_trabalha',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='endereco_complemento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='score_aluno',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone_secundario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='como_soube',
            field=models.CharField(blank=True, choices=[('Redes Sociais', 'Redes Sociais'), ('Site Prefeitura', 'Site Prefeitura'), ('Amigo', 'Amigo'), ('Panfleto', 'Panfleto'), ('Outros', 'Outros')], max_length=50, null=True, verbose_name='Como soube do curso?'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cor_raca',
            field=models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indigena', 'Indígena')], max_length=20, null=True, verbose_name='Cor/Raça'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='deficiencia',
            field=models.BooleanField(default=False, verbose_name='Possui alguma deficiência?'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Medio Incompleto', 'Médio Incompleto'), ('Medio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo')], max_length=50, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='num_moradores',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de Moradores'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='orgao_exp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Expedidor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='quantos_trabalham',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantos Trabalham'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='renda_individual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Individual'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='renda_moradores',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda dos Outros Moradores'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_profissional',
            field=models.CharField(blank=True, choices=[('Desempregado', 'Desempregado'), ('Autonomo', 'Autônomo'), ('Empregado', 'Empregado'), ('Estudante', 'Estudante'), ('Auxilio', 'Auxílio'), ('INSS', 'INSS')], max_length=20, null=True, verbose_name='Situação Profissional'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tempo_moradia',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural'), ('Menos de 5 anos', 'Menos de 5 anos'), ('Mais de 5 anos', 'Mais de 5 anos')], max_length=20, null=True, verbose_name='Tempo de Moradia'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_moradia',
            field=models.CharField(blank=True, choices=[('Propria', 'Própria'), ('Financiada', 'Financiada'), ('Alugada', 'Alugada'), ('Cedida', 'Cedida')], max_length=20, null=True, verbose_name='Tipo de Moradia'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='uf_naturalidade',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF da Naturalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cursos_interesse',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email_principal',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Principal'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_rua',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='escolas.escola', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone_principal',
            field=models.CharField(max_length=20, verbose_name='Telefone Principal'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos_interesse',
            field=models.ManyToManyField(blank=True, to='cursos.tipocurso', verbose_name='Cursos de Interesse'),
        ),
    ]
