# Generated by Django 5.2.8 on 2025-11-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_aluno_cargo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='valor_moradia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Moradia'),
        ),
    ]
