# Generated by Django 5.2.8 on 2025-11-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_valor_moradia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='score_total',
            field=models.IntegerField(default=0, editable=False, verbose_name='Score Total'),
        ),
    ]
