# Generated by Django 5.2.8 on 2025-11-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_score_total'),
        ('escolas', '0003_remove_escola_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterUniqueTogether(
            name='aluno',
            unique_together={('escola', 'cpf')},
        ),
    ]
