# Generated by Django 5.2.8 on 2025-11-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_aluno_cpf_alter_aluno_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email_principal',
            field=models.EmailField(max_length=254, verbose_name='Email Principal'),
        ),
    ]
