# Generated by Django 5.2.8 on 2026-03-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_alter_aluno_email_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email_principal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Principal'),
        ),
    ]
