# Generated by Django 5.2.8 on 2026-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_alter_aluno_email_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual a deficiência?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Principal'),
        ),
    ]
