# Generated by Django 5.2.8 on 2026-03-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_aluno_tipo_deficiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='receber_notificacoes',
            field=models.BooleanField(default=True, verbose_name='Deseja receber atualizações de cursos?'),
        ),
    ]
