# Generated by Django 5.2.8 on 2026-03-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_aluno_receber_notificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Histórico'),
        ),
    ]
