# Generated by Django 5.2.8 on 2026-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_aluno_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo'), ('Uniao Estavel', 'União Estável')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao_profissional',
            field=models.CharField(blank=True, choices=[('Desempregado', 'Desempregado'), ('Autonomo', 'Autônomo'), ('Empregado', 'Empregado'), ('Estudante', 'Estudante'), ('Auxilio', 'Auxílio'), ('INSS', 'INSS'), ('Aposentado', 'Aposentado')], max_length=20, null=True, verbose_name='Situação Profissional'),
        ),
    ]
