# Generated by Django 5.2.8 on 2026-04-01 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_alter_aluno_estado_civil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_alunos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='alunos.aluno', verbose_name='Aluno')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Arquivo do Aluno',
                'verbose_name_plural': 'Arquivos dos Alunos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
