# Generated by Django 5.2.8 on 2026-04-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_normalize_existing_alunos_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inclusao', models.PositiveIntegerField(verbose_name='Ano de Inclusão')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_social_record', to='alunos.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Membro Web Social',
                'verbose_name_plural': 'Membros Web Social',
                'ordering': ['-data_inclusao'],
            },
        ),
    ]
