# Generated by Django 5.2.8 on 2026-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_websocialmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turno_interesse',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10, null=True, verbose_name='Turno de Interesse'),
        ),
    ]
