# Generated by Django 5.2.8 on 2026-04-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0015_aluno_turno_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turno_interesse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turno de Interesse'),
        ),
    ]
