# Generated by Django 5.2.8 on 2026-07-08 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_alter_aluno_turno_interesse'),
        ('cursos', '0027_contatomatricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('add', 'Adicionado'), ('remove', 'Removido')], max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesse_logs', to='alunos.aluno')),
                ('tipo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.tipocurso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Interesse',
                'verbose_name_plural': 'Logs de Interesses',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
