# Generated by Django 5.2.8 on 2026-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0017_interesselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='from_publico',
            field=models.BooleanField(default=False, verbose_name='Cadastro via Link Público'),
        ),
    ]
