# Generated by Django 5.2.8 on 2026-08-01 04:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0018_aluno_from_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoaluno',
            name='arquivo',
            field=models.FileField(upload_to='documentos_alunos/%Y/%m/%d/', validators=[core.validators.validate_upload_file], verbose_name='Arquivo'),
        ),
    ]
