# Generated by Django 5.2.16 on 2026-08-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_alter_arquivoaluno_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
