# Generated by Django 5.0.6 on 2024-07-29 18:56

from django.db import migrations

def create_user_groups(apps, schema_editor):
    """
    Cria os grupos de usuário 'Coordenador' e 'Auxiliar Administrativo'.
    """
    Group = apps.get_model('auth', 'Group')
    
    groups_to_create = [
        'Coordenador',
        'Auxiliar Administrativo',
    ]
    
    for group_name in groups_to_create:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]