# Generated by Django 5.0.6 on 2024-07-30 12:00

from django.db import migrations

def assign_permissions_to_groups(apps, schema_editor):
    """
    Atribui as permissões para os grupos Coordenador e Auxiliar Administrativo.
    """
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Permissões para o Coordenador
    coordenador_permissions = [
        # Permissões de Alunos
        'add_aluno', 'change_aluno', 'delete_aluno', 'view_aluno',
        # Permissões de Cursos
        'add_curso', 'change_curso', 'delete_curso', 'view_curso',
        # Permissões de Tipos de Curso
        'add_tipocurso', 'change_tipocurso', 'delete_tipocurso', 'view_tipocurso',
        # Permissões de Inscrição
        'add_inscricao', 'change_inscricao', 'delete_inscricao', 'view_inscricao',
        # Permissões de Usuários (para criar outros coordenadores/auxiliares)
        'add_user', 'change_user', 'view_user',
    ]

    coordenador_group, created = Group.objects.get_or_create(name='Coordenador')
    permissions_obj = Permission.objects.filter(codename__in=coordenador_permissions)
    coordenador_group.permissions.set(permissions_obj)

    # Permissões para o Auxiliar Administrativo
    auxiliar_permissions = [
        # Permissões de Alunos (só pode alterar e visualizar)
        'change_aluno', 'view_aluno',
        # Permissões de Inscrição (pode inscrever e visualizar)
        'add_inscricao', 'view_inscricao',
        # Permissões de Cursos (só pode visualizar)
        'view_curso',
        # Permissões de Tipos de Curso (só pode visualizar)
        'view_tipocurso',
    ]
    
    auxiliar_group, created = Group.objects.get_or_create(name='Auxiliar Administrativo')
    permissions_obj = Permission.objects.filter(codename__in=auxiliar_permissions)
    auxiliar_group.permissions.set(permissions_obj)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_groups'),
    ]

    operations = [
        migrations.RunPython(assign_permissions_to_groups),
    ]