# Generated by Django 5.0.6 on 2024-07-30 18:00

from django.db import migrations

def backfill_user_profiles(apps, schema_editor):
    """
    Cria um Profile para cada User existente que ainda não tenha um.
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('core', 'Profile')
    
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assign_permissions'),
    ]

    operations = [
        migrations.RunPython(backfill_user_profiles),
    ]