# Generated by Django 5.0.6 on 2024-08-01 10:00

from django.db import migrations


def set_larissa_admin_cp(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('core', 'Profile')
    try:
        user = User.objects.get(username='larissa1937')
    except User.DoesNotExist:
        return
    # Ensure profile exists
    profile, _ = Profile.objects.get_or_create(user=user)
    profile.nivel_acesso = 'ADMIN_CP'
    profile.save()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_backfill_profiles'),
    ]
    operations = [
        migrations.RunPython(set_larissa_admin_cp),
    ]
