# Generated by Django 5.2.8 on 2026-03-25 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='Desenvolvedor (Acesso a Updates)'),
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Atualização')),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('visualizado_por', models.ManyToManyField(blank=True, related_name='avisos_lidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso / Atualização',
                'verbose_name_plural': 'Avisos / Atualizações',
                'ordering': ['-data_postagem'],
            },
        ),
    ]
