# Generated by Django 5.2.8 on 2026-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_is_developer_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel_acesso',
            field=models.CharField(choices=[('ADMIN_CP', 'Administrador de CPs'), ('ADMIN_UDITECH', 'Administrador de Uditechs'), ('SUPERUSER', 'Superusuário Global')], default='ADMIN_CP', max_length=20, verbose_name='Nível de Acesso Administrativo'),
        ),
    ]
