# Generated by Django 5.2.8 on 2026-06-09 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_email_destinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.BooleanField(default=True, verbose_name='Segunda-feira')),
                ('terca', models.BooleanField(default=True, verbose_name='Terça-feira')),
                ('quarta', models.BooleanField(default=True, verbose_name='Quarta-feira')),
                ('quinta', models.BooleanField(default=True, verbose_name='Quinta-feira')),
                ('sexta', models.BooleanField(default=True, verbose_name='Sexta-feira')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('horario_envio', models.TimeField(default='18:00', verbose_name='Horário de Envio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Envio Automático Ativo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Agendamento de E-mail',
                'verbose_name_plural': 'Agendamento de E-mail',
            },
        ),
    ]
