# Generated by Django 5.2.8 on 2026-06-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_set_larissa_admin_cp'),
        ('core', '0009_add_agendamento_email'),
        ('core', '0009_ensure_larissa_admin_cp'),
    ]

    operations = [
    ]
