# Generated by Django 5.2.8 on 2026-06-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260623_2046'),
        ('core', '0010_merge_20260623_2053'),
    ]

    operations = [
    ]
