# Generated by Django 5.2.8 on 2026-07-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260623_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildestinatario',
            name='receber_cp',
            field=models.BooleanField(default=True, verbose_name='Receber dados de CPs'),
        ),
        migrations.AddField(
            model_name='emaildestinatario',
            name='receber_sine',
            field=models.BooleanField(default=True, verbose_name='Receber dados do SINE'),
        ),
        migrations.AddField(
            model_name='emaildestinatario',
            name='receber_uditech',
            field=models.BooleanField(default=True, verbose_name='Receber dados de Uditechs'),
        ),
    ]
