# Generated by Django 5.2.16 on 2026-08-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emaildestinatario_receber_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nivel_acesso',
            field=models.CharField(choices=[('NENHUM', 'Nenhum (padrão — Coordenador/Auxiliar de uma escola)'), ('ADMIN_CP', 'Administrador de CPs'), ('ADMIN_UDITECH', 'Administrador de Uditechs'), ('SUPERUSER', 'Superusuário Global')], default='NENHUM', max_length=20, verbose_name='Nível de Acesso Administrativo'),
        ),
    ]
