# Generated by Django 5.2.8 on 2026-04-01 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0006_escola_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo', models.FileField(upload_to='documentos_escola/%Y/%m/%d/', verbose_name='Arquivo')),
                ('categoria', models.CharField(choices=[('pedagogico', 'Pedagógico'), ('administrativo', 'Administrativo'), ('financeiro', 'Financeiro'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('tamanho', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('extensao', models.CharField(blank=True, max_length=10, verbose_name='Extensão')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='escolas.escola')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento da Unidade',
                'verbose_name_plural': 'Documentos da Unidade',
                'ordering': ['-data_upload'],
            },
        ),
    ]
