# Generated by Django 5.2.8 on 2026-04-01 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('escolas', '0006_escola_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Pasta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='escolas.escola', verbose_name='Escola')),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='documentos.pasta', verbose_name='Pasta Pai')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
                'ordering': ['nome'],
                'unique_together': {('escola', 'nome', 'pasta_pai')},
            },
        ),
        migrations.AddField(
            model_name='documentounidade',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.pasta', verbose_name='Pasta'),
        ),
    ]
