# Generated by Django 5.2.8 on 2026-04-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_pasta_documentounidade_pasta'),
        ('escolas', '0006_escola_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentounidade',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='escolas.escola'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='escolas.escola', verbose_name='Escola'),
        ),
    ]
