# Generated by Django 5.2.8 on 2026-08-01 04:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documentounidade_escola_alter_pasta_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentounidade',
            name='arquivo',
            field=models.FileField(upload_to='documentos_escola/%Y/%m/%d/', validators=[core.validators.validate_upload_file], verbose_name='Arquivo'),
        ),
    ]
