# Generated by Django 5.2.9 on 2025-12-09 15:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0003_remove_escola_coordenador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('atendimento', models.IntegerField(default=0)),
                ('inscricoes', models.IntegerField(default=0)),
                ('pessoas_presentes', models.IntegerField(default=0)),
                ('ligacoes_recebidas', models.IntegerField(default=0)),
                ('ligacoes_realizadas', models.IntegerField(default=0)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_diarios', to='escolas.escola')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controle Diário',
                'verbose_name_plural': 'Controles Diários',
                'ordering': ['-data', 'escola__nome'],
                'unique_together': {('escola', 'data')},
            },
        ),
    ]
