# Generated by Django 5.2.8 on 2026-07-14 00:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDiarioSine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, unique=True, verbose_name='Data do Relatório')),
                ('atendimento_trabalhador', models.PositiveIntegerField(default=0, verbose_name='Atendimento ao Trabalhador')),
                ('atendimento_trabalhador_online', models.PositiveIntegerField(default=0, verbose_name='Atendimento ao Trabalhador On-line')),
                ('atendimento_empregador', models.PositiveIntegerField(default=0, verbose_name='Atendimento ao Empregador')),
                ('atendimento_empregador_online', models.PositiveIntegerField(default=0, verbose_name='Atendimento ao Empregador On-line')),
                ('seguro_desemprego', models.PositiveIntegerField(default=0, verbose_name='Seguro Desemprego')),
                ('ctps_digital', models.PositiveIntegerField(default=0, verbose_name='CTPS Digital')),
                ('vagas_captadas', models.PositiveIntegerField(default=0, verbose_name='Vagas Captadas')),
                ('curriculos', models.PositiveIntegerField(default=0, verbose_name='Currículos')),
                ('entrevistados', models.PositiveIntegerField(default=0, verbose_name='Entrevistados')),
                ('processo_seletivo', models.PositiveIntegerField(default=0, verbose_name='Processo Seletivo')),
                ('orientacao_profissional', models.PositiveIntegerField(default=0, verbose_name='Orientação Profissional')),
                ('ligacoes_recebidas', models.PositiveIntegerField(default=0, verbose_name='Número de Ligações Recebidas')),
                ('ligacoes_realizadas', models.PositiveIntegerField(default=0, verbose_name='Número de Ligações Realizadas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
            ],
            options={
                'verbose_name': 'Relatório Diário do SINE',
                'verbose_name_plural': 'Relatórios Diários do SINE',
                'ordering': ['-data'],
            },
        ),
    ]
