# Generated by Django 5.2.8 on 2025-11-13 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('escolas', '0002_escola_coordenador_user_alter_escola_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_curso', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipos de Curso',
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='cursos.tipocurso'),
        ),
    ]
