# Generated by Django 5.2.8 on 2025-11-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_tipocurso_curso_tipo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('cursando', 'Cursando'), ('concluido', 'Concluído'), ('desistente', 'Desistente')], default='cursando', max_length=10, verbose_name='Status'),
        ),
    ]
