# Generated by Django 5.2.8 on 2025-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_inscricao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocurso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
