# Generated by Django 5.2.8 on 2025-11-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_tipocurso_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10, null=True),
        ),
    ]
