# Generated by Django 5.2.8 on 2025-11-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_horario_curso_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocurso',
            name='cor',
            field=models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('danger', 'Vermelho'), ('warning', 'Amarelo'), ('info', 'Ciano'), ('secondary', 'Cinza'), ('dark', 'Preto')], default='primary', max_length=20, verbose_name='Cor'),
        ),
    ]
