# Generated by Django 5.2.8 on 2025-11-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_tipocurso_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocurso',
            name='cor',
            field=models.CharField(choices=[('primary', 'Azul Principal'), ('secondary', 'Cinza Secundário'), ('success', 'Verde Sucesso'), ('danger', 'Vermelho Perigo'), ('warning', 'Amarelo Aviso'), ('info', 'Ciano Informação'), ('light', 'Cinza Claro'), ('dark', 'Preto Escuro')], default='primary', max_length=20, verbose_name='Cor'),
        ),
    ]
