# Generated by Django 5.2.8 on 2025-11-19 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_tipocurso_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(default=datetime.date.today, verbose_name='Data da Aula')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aula', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Registro de Aula',
                'verbose_name_plural': 'Registros de Aulas',
                'ordering': ['-data_aula'],
                'unique_together': {('curso', 'data_aula')},
            },
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_presenca', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Ausência Justificada')], default='A', max_length=1, verbose_name='Status de Presença')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='cursos.inscricao', verbose_name='Inscrição')),
                ('registro_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='cursos.registroaula', verbose_name='Registro de Aula')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
                'ordering': ['inscricao__aluno__nome_completo'],
                'unique_together': {('registro_aula', 'inscricao')},
            },
        ),
    ]
