# Generated by Django 5.2.8 on 2025-11-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_registroaula_chamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dia_fim_semana',
            field=models.CharField(blank=True, choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='dia_inicio_semana',
            field=models.CharField(blank=True, choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
