# Generated by Django 5.2.9 on 2025-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_curso_dia_fim_semana_curso_dia_inicio_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Arquivado', 'Arquivado')], max_length=20),
        ),
    ]
