# Generated by Django 5.2.8 on 2026-03-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_curso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_professor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Professor'),
        ),
    ]
