# Generated by Django 5.2.8 on 2026-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_curso_nome_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='parceiro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Parceiro'),
        ),
    ]
