# Generated by Django 5.2.8 on 2026-03-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_curso_parceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='vagas',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Vagas'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='cor',
            field=models.CharField(choices=[('primary', 'Azul Principal'), ('secondary', 'Cinza Secundário'), ('success', 'Verde Sucesso'), ('danger', 'Vermelho Perigo'), ('warning', 'Amarelo Aviso'), ('info', 'Ciano Informação'), ('light', 'Cinza Claro'), ('dark', 'Preto Escuro'), ('indigo', 'Anil (Indigo)'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('orange', 'Laranja'), ('teal', 'Verde Água (Teal)')], default='primary', max_length=20, verbose_name='Cor'),
        ),
    ]
