# Generated by Django 5.2.8 on 2026-03-27 02:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_curso_vagas_alter_tipocurso_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='token_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Token de Acesso'),
        ),
    ]
