# Generated by Django 5.2.8 on 2026-03-27 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_curso_token_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='token_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Acesso'),
        ),
    ]
