# Generated by hand for data fix
import uuid
from django.db import migrations

def generate_unique_tokens(apps, schema_editor):
    Curso = apps.get_model('cursos', 'Curso')
    for curso in Curso.objects.all():
        curso.token_acesso = uuid.uuid4()
        curso.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_curso_token_acesso'),
    ]

    operations = [
        migrations.RunPython(generate_unique_tokens, reverse_code=migrations.RunPython.noop),
    ]
