# Generated by Django on 2026-03-27
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_generate_unique_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='token_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Acesso'),
        ),
    ]
