# Generated by Django 5.2.8 on 2026-03-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_alter_curso_token_acesso_unique'),
        ('escolas', '0006_escola_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Arquivado', 'Arquivado')], default='Aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Parceiro')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parceiros', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='cursos.parceiro', verbose_name='Parceiro'),
        ),
    ]
