# Generated by Django 5.2.8 on 2026-03-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_alter_curso_status_parceiro_alter_curso_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmentaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Ementa')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Programático')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ementa Padrão',
                'verbose_name_plural': 'Ementas Padrão',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='ementa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_curso', to='cursos.ementapadrao', verbose_name='Ementa Padrão'),
        ),
    ]
