# Generated by Django 5.2.8 on 2026-03-31 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_ementapadrao_tipocurso_ementa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('c1_1', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Conteúdo cumprido')),
                ('c1_2', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Material didático')),
                ('c1_3', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Recursos audiovisuais')),
                ('c2_1', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Domínio consultor')),
                ('c2_2', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Abordagem assuntos')),
                ('c2_3', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Clima participação')),
                ('c2_4', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Objetividade')),
                ('c2_5', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Técnicas didáticas')),
                ('c2_6', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Esclarecimento dúvidas')),
                ('c2_7', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Considerou solicitações')),
                ('c2_8', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Cumpriu horários')),
                ('c2_9', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Compareceu dias')),
                ('c3_1', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Espaço e instalações')),
                ('c3_2', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Processo inscrição')),
                ('c3_3', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Atendimento coordenação')),
                ('c3_4', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Carga horária')),
                ('c4_1', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Segurança aprendizagem')),
                ('c4_2', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Compromissos trabalho')),
                ('c4_3', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Participação aulas')),
                ('c4_4', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Integração colegas')),
                ('como_soube', models.CharField(choices=[('Cartaz', 'Cartaz, folder'), ('Internet', 'Internet'), ('Jornal', 'Jornal'), ('Televisao', 'Televisão'), ('Outros', 'Outros')], max_length=20, verbose_name='Como soube')),
                ('como_soube_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outros divulgação')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários/Sugestões')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_aluno', to='cursos.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Avaliação do Aluno (Curso)',
                'verbose_name_plural': 'Avaliações do Aluno (Cursos)',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoProfessorAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_nome', models.CharField(max_length=200, verbose_name='Nome do Professor')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('conceptual_pratico', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Conceitual - Prático')),
                ('conceptual_teorico', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Conceitual - Teórico')),
                ('conceptual_nota', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Conceitual - Nota')),
                ('behavioral_pratico', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Comportamental - Assiduidade')),
                ('behavioral_teorico', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Comportamental - Interesse')),
                ('behavioral_nota', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Comportamental - Visual')),
                ('attitudinal_pratico', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Atitudinal - Relacionamento Interpessoal')),
                ('attitudinal_teorico', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Atitudinal - Comunicação')),
                ('attitudinal_nota', models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Atitudinal - Criatividade')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_professor', to='cursos.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Avaliação do Professor (Aluno)',
                'verbose_name_plural': 'Avaliações do Professor (Alunos)',
            },
        ),
    ]
