# Generated by Django 5.2.8 on 2026-04-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_avaliacaoalunocurso_avaliacaoprofessoraluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='motivo_falta',
            field=models.CharField(blank=True, choices=[('Medico', 'Médico'), ('Doenca', 'Doença'), ('Trabalho', 'Trabalho'), ('Escola', 'Escola'), ('Transporte', 'Transporte'), ('Familia', 'Problemas Familiares'), ('Viagem', 'Viagem'), ('Luto', 'Falecimento'), ('Consulta', 'Consulta Médica'), ('Outros', 'Outros')], max_length=20, null=True, verbose_name='Motivo da Falta'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='motivo_falta_outro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outro Motivo'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_1',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Conhecimento do Instrutor'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_2',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Forma de ensinar'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_3',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Estímulo à participação'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_4',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Objetividade e Clareza'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_5',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Técnicas de ensino'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_6',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Esclarecimento de dúvidas'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_7',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Atenção às solicitações'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_8',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Cumprimento de horários'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c2_9',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Assiduidade (Presença)'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c3_1',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Espaço e Instalações'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c3_2',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Facilidade na inscrição'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c3_3',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Atendimento da coordenação'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c3_4',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Carga horária adequada'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c4_1',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Aprendizado adquirido'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c4_2',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Pontualidade própria'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c4_3',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Minha participação'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalunocurso',
            name='c4_4',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Relacionamento com colegas'),
        ),
        migrations.AlterField(
            model_name='avaliacaoprofessoraluno',
            name='behavioral_nota',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Apresentação Pessoal'),
        ),
        migrations.AlterField(
            model_name='avaliacaoprofessoraluno',
            name='behavioral_pratico',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Assiduidade e Pontualidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaoprofessoraluno',
            name='behavioral_teorico',
            field=models.CharField(choices=[('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10, verbose_name='Interesse e Participação'),
        ),
    ]
