# Generated by Django 5.2.8 on 2026-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_chamada_motivo_falta_chamada_motivo_falta_outro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaula',
            name='nao_houve_aula',
            field=models.BooleanField(default=False, verbose_name='Não houve aula (Feriado/Recesso)'),
        ),
    ]
