# Generated by Django 5.2.8 on 2026-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_registroaula_nao_houve_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_desistencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desistência'),
        ),
    ]
