# Generated by Django 5.2.8 on 2026-04-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0023_inscricao_data_conclusao_inscricao_data_desistencia'),
        ('cursos', '0023_merge_20260415_0833'),
    ]

    operations = [
    ]
