# Generated by Django 5.2.8 on 2026-04-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_merge_20260409_0025'),
        ('cursos', '0024_merge_20260422_1119'),
    ]

    operations = [
    ]
