# Generated by Django 5.2.8 on 2026-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0025_merge_20260422_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='telefone_professor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp/Telefone do Professor'),
        ),
    ]
