# Generated by Django 5.2.8 on 2026-05-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_alter_aluno_turno_interesse'),
        ('cursos', '0026_curso_telefone_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_contatado', 'Não Contatado'), ('tentativa_1', '1ª Tentativa (Sem Resposta)'), ('tentativa_2', '2ª Tentativa (Sem Resposta)'), ('tentativa_3', '3ª Tentativa (Sem Resposta)'), ('contatado', 'Contatado (Em Conversa)'), ('interessado', 'Interessado (Matricular)'), ('recusou', 'Recusou / Sem Interesse'), ('numero_invalido', 'Número Inválido')], default='nao_contatado', max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_matricula', to='alunos.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_matricula', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Contato de Matrícula',
                'verbose_name_plural': 'Contatos de Matrícula',
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
