# Generated by Django 5.2.16 on 2026-08-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0027_contatomatricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Arquivado', 'Arquivado')], db_index=True, default='Aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('cursando', 'Cursando'), ('concluido', 'Concluído'), ('desistente', 'Desistente')], db_index=True, default='cursando', max_length=10, verbose_name='Status'),
        ),
    ]
