"""
Django settings for gestao_qualificacao_profissional project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar arquivo .env se existir (sem sobrepor variaveis ja existentes)
env_file = BASE_DIR / '.env'
if env_file.exists():
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                os.environ.setdefault(key.strip(), val.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# A chave DEVE vir da variavel de ambiente (arquivo .env / secrets do Docker).
# Nunca versione a chave de producao.
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

if not SECRET_KEY:
    if DEBUG:
        # Fallback APENAS para desenvolvimento local. Nao usar em producao.
        SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise RuntimeError(
            'SECRET_KEY nao definida. Configure a variavel de ambiente SECRET_KEY '
            'antes de iniciar em producao.'
        )

# Hosts permitidos (separados por virgula na variavel de ambiente ALLOWED_HOSTS).
ALLOWED_HOSTS = [
    h.strip() for h in os.getenv(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,100.93.40.101,'
        'servidor-qualificacao.tailbeb7d5.ts.net,'
        'app.gestaoqualificacao.com.br,.gestaoqualificacao.com.br'
    ).split(',') if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://100.93.40.101',
    'http://100.93.40.101:8000',
    'http://100.93.40.101:7681',
    'https://servidor-qualificacao.tailbeb7d5.ts.net',
    'https://app.gestaoqualificacao.com.br',
    'https://*.gestaoqualificacao.com.br',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies de sessão/CSRF nao devem vazar em requisicoes cross-site.
# Nenhum template le o cookie de CSRF via JS (todos usam {{ csrf_token }} ou o
# campo hidden csrfmiddlewaretoken), entao e seguro barrar leitura via JS.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True

# --- FLAGS DE SEGURANCA (aplicadas apenas fora de DEBUG / em producao) ---
if not DEBUG:
    # Cookies apenas via HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    # Redireciona HTTP -> HTTPS (desligavel via env caso o proxy ja force TLS)
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    # HSTS: 1 ano, incluindo subdominios
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Impede o navegador de adivinhar o content-type
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Referrer minimo
    SECURE_REFERRER_POLICY = 'same-origin'


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My apps
    'core.apps.CoreConfig',
    'escolas',
    'cursos',
    'alunos',
    'usuarios',
    'score_config',
    'documentos',
    'declaracao.apps.DeclaracaoConfig',
    'controle_diario', # Novo app
    # 'whatsapp',
    'treinamento',
    'publico',

    # Apps de terceiros
    'dbbackup',
    'channels',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ThreadLocalUserMiddleware',
    'core.middleware.AdminContextMiddleware',
]

ROOT_URLCONF = 'gestao_qualificacao_profissional.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'gestao_qualificacao_profissional' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.avisos_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestao_qualificacao_profissional.wsgi.application'
ASGI_APPLICATION = 'gestao_qualificacao_profissional.asgi.application'

REDIS_HOST = os.getenv('REDIS_HOST')

if REDIS_HOST:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(REDIS_HOST, 6379)],
            },
        },
    }
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv('REDIS_CACHE_URL', f"redis://{REDIS_HOST}:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'core:login_success'
LOGOUT_REDIRECT_URL = '/'

# --- CONFIGURAÇÃO DE E-MAIL ---
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.resend.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'resend')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'onboarding@resend.dev')

# --- CONFIGURAÇÃO DE BACKUP (django-dbbackup + Google Cloud Storage) ---
# A chave de service account e opcional fora de producao: sem ela, o app ainda
# sobe normalmente (so o comando `manage.py dbbackup` fica indisponivel).
# Caminho configuravel via env para nao acoplar todo boot local a esse arquivo.
GS_BUCKET_NAME = 'backup-django-qualificacao-2026'
GS_PROJECT_ID = 'backup-django-2026'

_gs_key_path = os.getenv(
    'GOOGLE_DRIVE_KEY_PATH', os.path.join(BASE_DIR, 'google_drive_key.json')
)

if os.path.exists(_gs_key_path):
    from google.oauth2 import service_account

    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(_gs_key_path)
    _dbbackup_storage = {
        "dbbackup": {"BACKEND": "storages.backends.gcloud.GoogleCloudStorage"},
    }
elif not DEBUG:
    raise RuntimeError(
        f'Chave de service account do Google nao encontrada em "{_gs_key_path}". '
        'Configure GOOGLE_DRIVE_KEY_PATH ou coloque google_drive_key.json na raiz '
        'do projeto antes de iniciar em producao.'
    )
else:
    # Dev sem a chave: backup para GCS fica indisponivel, mas o app sobe.
    _dbbackup_storage = {
        "dbbackup": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    }

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    **_dbbackup_storage,
}

# Número de backups para manter (apaga os mais antigos automaticamente).
# O fluxo de backup real hoje usa pg_dump direto (backup_agora.sh/backup_gcs.sh,
# retencao de 10), nao o "manage.py dbbackup" — mas o bucket GCS e compartilhado
# entre os dois, entao manter isto em 1 era uma armadilha: se alguem rodar
# "manage.py dbbackup" manualmente, apagaria os backups da retencao real.
DBBACKUP_CLEANUP_KEEP = 10
DBBACKUP_CLEANUP_KEEP_MEDIA = 10

# --- CONFIGURAÇÃO DE E-MAIL REAL FINALIZADA ---

from django.contrib.messages import constants as messages_constants

MESSAGE_TAGS = {
    messages_constants.DEBUG: 'secondary',
    messages_constants.INFO: 'info',
    messages_constants.SUCCESS: 'success',
    messages_constants.WARNING: 'warning',
    messages_constants.ERROR: 'danger',
}

# Permitir visualização de arquivos (PDFs) em iframes
X_FRAME_OPTIONS = 'SAMEORIGIN'

# --- LOGGING ---
# Antes disso o projeto não tinha NENHUM LOGGING configurado: erros de
# auditoria/notificação (varios `except Exception as e: print(...)`
# espalhados pelas views) só apareciam se alguem estivesse olhando o stdout
# do container no exato momento. Isso adiciona um arquivo persistente
# (dentro do bind mount, sobrevive a restart do container) + mantém o
# console (docker logs) — não muda nenhuma lógica de negócio, só onde os
# logs vão parar. Handlers/loggers padrão do Django (`django.request` etc.)
# continuam funcionando normalmente, isto só formaliza e persiste.
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
