# Generated by Django 5.2.8 on 2025-11-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='coordenador_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escola_coordenada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
