# Generated by Django 5.2.8 on 2025-11-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_escola_coordenador_user_alter_escola_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='coordenador',
        ),
    ]
