# Generated by Django 5.2.8 on 2026-03-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_remove_escola_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
