# Generated by Django 5.2.8 on 2026-03-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_alter_escola_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
