# Generated by Django 5.2.8 on 2026-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_escola_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='tipo',
            field=models.CharField(choices=[('CP', 'Centro Profissionalizante'), ('UDITECH', 'Uditech')], default='CP', max_length=15, verbose_name='Tipo de Escola'),
        ),
    ]
