# Generated by Django 5.2.8 on 2026-07-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_escola_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
