# Generated by Django 5.2.16 on 2026-08-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0009_populate_escola_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='tipo',
            field=models.CharField(choices=[('CP', 'Centro Profissionalizante'), ('UDITECH', 'Uditech')], db_index=True, default='CP', max_length=15, verbose_name='Tipo de Escola'),
        ),
    ]
