# Generated by Django 5.2.8 on 2026-03-19 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0006_escola_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(help_text='Nome único da instância na Evolution API (ex: escola-morumbi)', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando...'), ('connected', 'Conectado'), ('error', 'Erro')], default='disconnected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp',
                'verbose_name_plural': 'Configurações WhatsApp',
            },
        ),
    ]
