# Generated by Django 5.2.9 on 2025-12-08 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0009_curso_dia_fim_semana_curso_dia_inicio_semana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(editable=False)),
                ('status_aplicado', models.CharField(choices=[('concluido', 'Concluído'), ('matriculado', 'Matriculado'), ('cursando', 'Cursando')], editable=False, max_length=20)),
                ('assinatura_digital', models.TextField(blank=True, help_text='Armazena a assinatura em formato Base64', null=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('hash_validacao', models.CharField(blank=True, help_text='Hash para validar a autenticidade do documento', max_length=64, unique=True)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaracoes_emitidas', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes', to='cursos.inscricao')),
            ],
        ),
    ]
