# Generated by Django 5.2.8 on 2025-11-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembrosTrabalhamFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('qtd_maior_ou_igual', models.IntegerField(help_text='A pontuação será aplicada se a quantidade de membros que trabalham for MAIOR OU IGUAL A este valor.')),
            ],
            options={
                'verbose_name': 'Faixa de Membros que Trabalham',
                'verbose_name_plural': '4. Faixas de Membros que Trabalham',
                'ordering': ['-qtd_maior_ou_igual'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumeroMoradoresFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('qtd_maior_ou_igual', models.IntegerField(help_text='A pontuação será aplicada se o número de moradores for MAIOR OU IGUAL A este valor.')),
            ],
            options={
                'verbose_name': 'Faixa de Número de Moradores',
                'verbose_name_plural': '3. Faixas de Número de Moradores',
                'ordering': ['-qtd_maior_ou_igual'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RendaFamiliarFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('valor_maior_que', models.DecimalField(decimal_places=2, help_text='A pontuação será aplicada se a renda familiar for MAIOR QUE este valor.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Faixa de Renda Familiar',
                'verbose_name_plural': '1. Faixas de Renda Familiar',
                'ordering': ['-valor_maior_que'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RendaPerCapitaFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('valor_maior_que', models.DecimalField(decimal_places=2, help_text='A pontuação será aplicada se a renda per capita for MAIOR QUE este valor.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Faixa de Renda Per Capita',
                'verbose_name_plural': '2. Faixas de Renda Per Capita',
                'ordering': ['-valor_maior_que'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempoMoradiaFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('titulo', models.CharField(choices=[('Natural', 'Natural'), ('Menos de 5 anos', 'Menos de 5 anos'), ('Mais de 5 anos', 'Mais de 5 anos')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Faixa de Tempo de Moradia',
                'verbose_name_plural': '5. Faixas de Tempo de Moradia',
                'ordering': ['titulo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMoradiaFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('titulo', models.CharField(choices=[('Propria', 'Própria'), ('Financiada', 'Financiada'), ('Alugada', 'Alugada'), ('Cedida', 'Cedida')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Faixa de Tipo de Moradia',
                'verbose_name_plural': '6. Faixas de Tipo de Moradia',
                'ordering': ['titulo'],
                'abstract': False,
            },
        ),
    ]
