# Generated by Django 5.2.8 on 2026-04-14 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Aula')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / O que aprender')),
                ('youtube_url', models.URLField(verbose_name='URL do Vídeo (YouTube)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Vídeo de Treinamento',
                'verbose_name_plural': 'Vídeos de Treinamento',
                'ordering': ['ordem', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_conclusao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_treinamento', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='treinamento.videotreinamento')),
            ],
            options={
                'verbose_name': 'Progresso de Treinamento',
                'verbose_name_plural': 'Progressos de Treinamento',
                'unique_together': {('usuario', 'video')},
            },
        ),
    ]
